# Generated by Django 5.1 on 2024-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('servico', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('contribuinte', models.BooleanField(default=False)),
                ('contribuinte_numero', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
